<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1 - Sri Region</name>
   <tag></tag>
   <elementGuidId>76a3e83b-515f-4476-a60b-a188f984fe9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmOrgHierachy']/table[4]/tbody/tr/td[2]/table[2]/tbody/tr/td/font/table/tbody/tr[4]/td/table/tbody/tr[2]/td/font/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>OrgDetail.asp?company%5Fid=1328&amp;org%5Fid=11134</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 - Sri Region</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOrgHierachy&quot;)/table[4]/tbody[1]/tr[1]/td[2]/table[2]/tbody[1]/tr[1]/td[1]/font[1]/table[1]/tbody[1]/tr[4]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/font[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmOrgHierachy']/table[4]/tbody/tr/td[2]/table[2]/tbody/tr/td/font/table/tbody/tr[4]/td/table/tbody/tr[2]/td/font/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/font/a</value>
   </webElementXpaths>
</WebElementEntity>
