<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_BuildPro</name>
   <tag></tag>
   <elementGuidId>73cca8f6-f138-4852-b6b0-1a27d7d905ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/a/font/b</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/table[2]/tbody[1]/tr[1]/td[5]/a[@class=&quot;welcome&quot;]/font[1]/b[1][count(. | //*[(text() = ' BuildPro ' or . = ' BuildPro ')]) = count(//*[(text() = ' BuildPro ' or . = ' BuildPro ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BuildPro </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[2]/tbody[1]/tr[1]/td[5]/a[@class=&quot;welcome&quot;]/font[1]/b[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/font/b</value>
   </webElementXpaths>
</WebElementEntity>
